### ISSUE TITLE
Does currency conversion account for inflation?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/pelican-backend#10]
The cumulative rate of inflation from 1999 to 2019 for USD is 54% https://www.usinflationcalculator.com

If we are converting, for example, EUR (1999) to USD (1999) for one contract value, and then EUR (2019) to USD (2019) for another contract value, the sum won't have the same unit, because USD (2019) is 54% inflated compared to USD (1999).

**Comment by hrubyjan** [comment]
The currency conversion only converts currencies related to the actual date of the tender. So if the amount is in EUR in 1999 the currency conversion only say how many USD is would be in 1999.

**Comment by jpmckinney** [comment]
Thanks - I added to docs in e269ab5
