### ISSUE TITLE
Error in Recognizing 'lifecycleImage' Tag

### ISSUE THREAD

**Issue by allakulov** [open-contracting/pelican-backend#101]
Encountered an error related to the 'lifecycleImage' tag when exporting a report for netherlands_2023-11-15 (Id 12) using the default English template. 

Full error message:
reason: The tag 'lifecycleImage' is not recognized. Please check the spelling and syntax.
full tag: {% lifecycleImage %}

Tried exporting a report to a template without the tag and it has worked.

**Comment by jpmckinney** [comment]
That tag had to occur within an "Overview" template. I created an overview template, and it should work now.
