### ISSUE TITLE
Filters are not working

### ISSUE THREAD

**Issue by allakulov** [open-contracting/pelican-backend#121]
The filters, including the SQL ILIKE filter functionality and the date filter, are not working as expected. 

Example: [netherlands_2024-05-23 ](https://pelican.open-contracting.org/overview/17)(Id 17) has a total of 
43,481 unique OCIDs. Filtering for `%minister%` suggests results for a subset of 2,542 OCIDs should be returned (see screenshot), although the original results for 43,481 OCIDs are retained.

![image](https://github.com/open-contracting/pelican-backend/assets/8681119/26566ece-c4e7-4606-832b-9fdb892da09e)

 In a similar manner, the date filter also does not return the expected results.

**Comment by jpmckinney** [comment]
Aha, we forgot to turn on the filter worker on the server. Try again :)

You should see a new dataset appear in the list if it is working.
