### ISSUE TITLE
Coherence: Release date

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/pelican-backend#124]
We have use cases for checking the quality of the release date, separately from its participation in other checks. Mainly: to check whether the release date has been implemented correctly (as it's a common implementation error).

We can repeat the release date checks from: contracting process timeline, milestone dates, amendment dates, document dates.

**Comment by jpmckinney** [comment]
Done in 2ce8c47

**Comment by fppenna** [comment]
A nice-to-have coherence test is evaluating whether the release date is in the future. I've seen this in Portland and can provide examples if needed.

**Comment by jpmckinney** [comment]
I've created a separate issue #135
