### ISSUE TITLE
Update checks to work with strings during numeric operations

### ISSUE THREAD

**Issue by hrubyjan** [open-contracting/pelican-backend#26]
We should always try to get a numeric value from the string when we expect number and we have text because it repeats that publisher publishes number as a string

If I remember correctly we can test it on a `nepal_dhangadhi`

**Comment by jpmckinney** [comment]
Can add a helper method, and a keyword argument to `deep_get` to perform type coercion.

**Comment by jpmckinney** [comment]
Grep'ing the release schema with:

    "type": (?!"(array|object|string)"|\[\n +"(array|boolean|object|string)"|{)

yields:

* durationInDays
* numberOfTenderers
* quantity (no related checks)
* amount

All those fields are retrieved using `deep_get(.., .., float)`.
