### ISSUE TITLE
Possible bug with OCID registered prefix failure 

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/pelican-backend#33]
For kenya_makueni all OCIDs fail data quality due to the prefix not being registered https://dqt.datlab.eu/field/148/detail/ocid, however checking https://standard.open-contracting.org/latest/en/implementation/registration/?highlight=prefix#ocid-prefix 'muq5cl' it looks like it is correctly registered.

**Comment by odscjen** [comment]
I've come across another instance of this, [https://dqt.datlab.eu/field/402/detail/ocid](https://dqt.datlab.eu/field/402/detail/ocid). The prefix was created on 2020-12-10 and the dataset processed on 2022-01-25.

The prefix doesn't appear to be in [the public sheet](https://docs.google.com/spreadsheets/d/1Am3gq0B77xN034-8hDjhb45wOuq-8qW6kGOdp40rN4M/pubhtml?gid=506986894&single=true&widget=true), but it is in the [internal list ocid prefix sheet](https://docs.google.com/spreadsheets/d/1Am3gq0B77xN034-8hDjhb45wOuq-8qW6kGOdp40rN4M/edit#gid=719166812).

**Comment by hrubyjan** [comment]
for the newly processed dataset this can be a problem because there were some changes in the source codes that force me to bypass the starter worker (which makes the ocid prefixes update) when processing the dataset. I did not try to solve this on our server and it's is slowly becoming obsolete.

**Comment by jpmckinney** [comment]
@odscjen I don't think Pelican has been updated with the fix in 5427afc. Once I finish deploying the registry, I'll deploy a new instance of Pelican which will contain the fix.

**Comment by yolile** [comment]
> The prefix doesn't appear to be in [the public sheet](https://docs.google.com/spreadsheets/d/1Am3gq0B77xN034-8hDjhb45wOuq-8qW6kGOdp40rN4M/pubhtml?gid=506986894&single=true&widget=true), but it is in the [internal list ocid prefix sheet](https://docs.google.com/spreadsheets/d/1Am3gq0B77xN034-8hDjhb45wOuq-8qW6kGOdp40rN4M/edit#gid=719166812).

Just for the record: I was checking the prefixes sheet today, and I found that the public list was filtered, so some prefixes weren't being displayed. Maybe that was the issue all this time? We'll never know, but I protected the public sheet now, so that shouldn't happen again.

**Comment by jpmckinney** [comment]
I guess it was both. The problem I fixed was a problem with other lists as well.

**Comment by yolile** [comment]
This is happening again with the Netherlands https://pelican.open-contracting.org/field/12/detail/ocid
cc @allakulov

**Comment by jpmckinney** [comment]
The code referred to the old spreadsheet. I've updated it to refer to the new one.

For now, just ignore this error for the Netherlands report.
