### ISSUE TITLE
RabbitMQ consumer creates multiple threads, but the global cursor is not thread-safe

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/pelican-backend#37]
https://www.psycopg.org/docs/cursor.html

> Cursors are not thread safe: a multithread application can create many cursors from the same connection and should use each cursor from a single thread. See Thread and process safety for details.

I think we need to change the db.py layer to return fresh cursors. (Cursors are cheap.) Maybe we just delete `global cursor` and add `cursor.close()` whenever we call `get_cursor()`.

@jakubkrafka Do you agree?

**Comment by jakubkrafka** [comment]
Fully agree, this makes sense.
