### ISSUE TITLE
Error with data that contains non numeric values in numeric fields

### ISSUE THREAD

**Issue by yolile** [open-contracting/pelican-backend#62]
E.g., when processing colombia_api (kingfisher collection_id 2579), which contains JSON like https://apiocds.colombiacompra.gov.co/apiCCE2.0/rest/release/ocid/ocds-k50g02-31496

Pelican throws:

``` bash
File "/usr/src/app/contracting_process/resource_level/consistent/tender_value.py", line 75, in calculate

    if (tender_value_amount > 0 and planning_budget_amount_amount < 0) or (
TypeError: '>' not supported between instances of 'dict' and 'int'

```

**Comment by jpmckinney** [comment]
Can be fixed by using `deep_get(..., force=int)` instead of indexing directly to `tender["value"]`, etc.
